name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: losdiasdebrisa-50f36
          workload_identity_provider: projects/449081498039/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-firebase-deploy@losdiasdebrisa-50f36.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Check authentication
        run: |
          gcloud auth list
          gcloud projects describe losdiasdebrisa-50f36

      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools@15.22.1
          firebase --version

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --project losdiasdebrisa-50f36 --non-interactive